/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TableContract } from "./TableContract";
export * as factories from "./factories";
export { TableContract__factory } from "./factories/TableContract__factory";
